// ===-------------------------------------------------------------------------------------------===
// Copyright © 2026 Jean Silva
//
// This file is part of the Pragma open-source project.
//
// This program is free software: you can redistribute it and/or modify it under the terms of the
// GNU General Public License as published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
// even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
// General Public License for more details.
//
// You should have received a copy of the GNU General Public License along with this program. If
// not, see https://www.gnu.org/licenses.
// ===-------------------------------------------------------------------------------------------===

extension Planner {
  /// Adds a ``Plan`` to this ``Planner`` based on an immutable model. The given model, referred to
  /// by this function as a "descriptor", influences only the user-defined properties of the
  /// ``Plan``; ones whose generation is a responsibility of the implementation of this protocol
  /// (such as the ID) are ignored.
  ///
  /// - Parameter descriptor: Immutable model on which the ``Plan`` will be based, probably
  ///   differing only in its ID, which will be generated by the implementation. The IDs *may*
  ///   match, but they are likely to be different in case the implementation defines one randomly.
  /// - Returns: The ID of the added ``Plan``.
  public func addPlan(
    basedOn descriptor: ReadOnlyPlan
  ) async throws(PlannerError<ImplementationError>) -> PlanType.ID {
    let addedPlanID = try addPlan(titled: descriptor.title, summarizedBy: descriptor.summary)
    let addedPlan = try plan(identifiedAs: addedPlanID)
    for goalDescriptor in descriptor.goals {
      _ = try await addedPlan.addGoal(basedOn: goalDescriptor)
    }
    return addedPlanID
  }
}

extension Plan {
  /// Adds a ``Goal`` to this ``Plan`` based on an immutable model. The given model, referred to by
  /// this function as a "descriptor", influences only the user-defined properties of the ``Goal``;
  /// ones whose generation is a responsibility of the implementation of this protocol (such as the
  /// ID) are ignored.
  ///
  /// - Parameter descriptor: Immutable model on which the ``Goal`` will be based, probably
  ///   differing only in its ID, which will be generated by the implementation. The IDs *may*
  ///   match, but they are likely to be different in case the implementation defines one randomly.
  /// - Returns: The ID of the added ``Goal``.
  public func addGoal(
    basedOn descriptor: ReadOnlyGoal
  ) async throws(PlannerError<ImplementationError>) -> GoalType.ID {
    let addedGoalID = try await addGoal(titled: descriptor.title, summarizedBy: descriptor.summary)
    let addedGoal = try await goal(identifiedAs: addedGoalID)
    for toDoDescriptor in descriptor.toDos {
      _ = try await addedGoal.addToDo(basedOn: toDoDescriptor)
    }
    return addedGoalID
  }
}

extension Goal {
  /// Adds a ``ToDo`` to this ``Goal`` based on an immutable model. The given model, referred to by
  /// this function as a "descriptor", influences only the user-defined properties of the ``ToDo``;
  /// ones whose generation is a responsibility of the implementation of this protocol (such as the
  /// ID) are ignored.
  ///
  /// - Parameter descriptor: Immutable model on which the ``ToDo`` will be based, probably
  ///   differing only in its ID, which will be generated by the implementation. The IDs *may*
  ///   match, but they are likely to be different in case the implementation defines one randomly.
  /// - Returns: The ID of the added ``ToDo``.
  public func addToDo(
    basedOn descriptor: ReadOnlyToDo
  ) async throws(PlannerError<ImplementationError>) -> ToDoType.ID {
    let addedToDoID = try await addToDo(
      titled: descriptor.title,
      summarizedBy: descriptor.summary,
      due: descriptor.deadline
    )
    guard descriptor.status != .idle else { return addedToDoID }
    let addedToDo = try await toDo(identifiedAs: addedToDoID)
    try await addedToDo.setStatus(to: descriptor.status)
    return addedToDoID
  }
}
